### ISSUE TITLE
Power score fluctuating 

### ISSUE THREAD

**Issue by Daniel-Cooper-D02an** [discovery-game/bugtracker#12]
**Describe the bug**
Power score is increased after an attack, it settles back to correct score after you build a ship

**To Reproduce**
1. Check power score before anything. 
2. Attack pirate / inactive with ships / active player
3. Check power score again

**Expected behavior**
Power score if anything would drop after a successful attack of you lost ships, never increase

**Screenshots**

**Informations (please complete the following information):**
 - Game version: 2.2.7
 - Server name: umbriel and ptr
 - Device: phone
 - OS: android
 - Version 

**Additional context**

**Comment by Neoz-JourneyLab** [comment]
Fixed
When militrary ships score was calculated, new flights back from attack and old attacking flights where taken in count in "military in flight"
