### ISSUE TITLE
Simply say No to Feature Request!

### ISSUE THREAD

**Issue by eNVy-oKay** [discovery-game/bugtracker#24]

**Comment by Daniel-Cooper-D02an** [comment]
Its not listed as a dependancy for building hess, the tech needed to build ships are listed on the ships themselves within the spaceport. The tech screen you show gives the information about which ships are affected by the tech, this screen is the ship screen in the spaceport, these screens are the only ones that show what the ship build is dependant on
![Screenshot_20210211-190354~3](https://user-images.githubusercontent.com/69074476/107685830-616a8180-6c9c-11eb-9ef9-93763b0b4cc6.png)

**Comment by CausticUrbanCoast** [comment]
**Suggestion
Either add Intrusion as a required Hess dependency or specify it as a non-dependent effect on Hess**

**Comment by Daniel-Cooper-D02an** [comment]
It wont be listed as a dependency as its not something that all players will use. Use of this tech is tactic related.

**Comment by CausticUrbanCoast** [comment]
As per above, this information is intended to be hidden from starting players.

**Comment by Daniel-Cooper-D02an** [comment]
It is not hidden as it is mentioned on the wiki page related to the technology that it will increase the size of the Hess ship, use of the technology is player related and down to their understanding of the impact of its use.

**Comment by antoine-pous** [comment]
@CausticUrbanCoast next time don't delete your comments please. 

Even if @Daniel-Cooper-D02an debate and known well our goals, an idea can be better than what we have done and can be implemented. If we reject a feature request we'll do it by ourselves and explain why we reject it.

Now your ticket is not readable, which is not useful to review your request 😅

I lock this useless thread, feel free to open a new one with your initial request.
