### ISSUE TITLE
Wiki Add Player Color Descriptions - Feature Request

### ISSUE THREAD

**Issue by eNVy-oKay** [discovery-game/bugtracker#26]
## Search Terms
Wiki Player Color Colors Colours Colour 

## Suggestion
Add to the Wiki a description on what the different player colors/colours mean

## Use Cases
Understanding why different players are different colors/colours

## Examples
![Leaderboard](https://user-images.githubusercontent.com/41645902/107691521-63aeea80-6c60-11eb-8f1e-2247cc64ce7d.jpg)
![Screenshot_20210211-115708_Discovery](https://user-images.githubusercontent.com/41645902/107691593-7a554180-6c60-11eb-8cae-ce10d8591439.jpg)
![Screenshot_20210211-115702_Discovery](https://user-images.githubusercontent.com/41645902/107691622-84774000-6c60-11eb-9714-8e6f47dcb0db.jpg)

**Comment by Daniel-Cooper-D02an** [comment]
Agreed, will be included
