### ISSUE TITLE
Screen

### ISSUE THREAD

**Issue by eNVy-oKay** [discovery-game/bugtracker#35]
![Screenshot_20210418-091953_Discovery.jpg](https://user-images.githubusercontent.com/41645902/115152866-d99c4d00-a027-11eb-9f1c-cc700358d267.jpg)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Informations (please complete the following information):**
 - Game version: [e.g. 1.2.0]
 - Server name: [e.g. Umbriel]
 - Device: [e.g. Desktop, iPhone6 etc...]

**Additional context**

**Comment by eNVy-oKay** [comment]
![Screenshot_20210424-192225_Discovery.jpg](https://user-images.githubusercontent.com/41645902/115978170-8c8e0e80-a532-11eb-9dcf-de0e111a46db.jpg)

**Comment by antoine-pous** [comment]
You should have an update on the store, if not kill your store app and retry.
