### ISSUE TITLE
GHQ building queue

### ISSUE THREAD

**Issue by Daniel-Cooper-D02an** [discovery-game/bugtracker#5]
**Describe the bug**
GHQ build shows error when you upgrade any building, build happens but gives error on client side. Reboot fixes error shown and countdown shows as it should

**To Reproduce**
1. Go to Alliance / GHQ
2. Click on any building to upgrade
3. See error

**Expected behavior**
Build starts and countdown shows

**Screenshots**
![Screenshot_20201004-220351](https://user-images.githubusercontent.com/69074476/96051673-f20e8d80-0e73-11eb-9da4-27cb2865e6cc.png)

**Informations (please complete the following information):**
 - Game version: 2.2.7
 - Server name: PTR / Umbriel
 - Device: 
 - OS: Android
 - Version 10

**Additional context**

**Comment by antoine-pous** [comment]
Fixed on the PTR, will be deployed with the next update
