### ISSUE TITLE
Heimdall build 1 by 1

### ISSUE THREAD

**Issue by Daniel-Cooper-D02an** [discovery-game/bugtracker#6]
**Describe the bug**
Only able to build heimdall 1 at a time, slider does not go over 1 and select amount defaults to 1

**To Reproduce**
1. Go to spaceport / heimdall 
2. Click on slider and try to increase amount
3. Click on and hold slider to bring up custom amount and type more than 1

**Expected behavior**
Slider will change depending on honor amount available 

**Screenshots**

**Informations (please complete the following information):**
 - Game version: 2.2.7
 - Server name: PTR
 - Device: 
 - OS: Android 
 - Version 10

**Additional context**

**Comment by antoine-pous** [comment]
Fixed with client v2.2.8
